spring.application.name=log-processor-service
server.port=${SERVER_PORT:8081}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

#spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:log-processor-group}
spring.kafka.consumer.auto-offset-reset=${KAFKA_AUTO_OFFSET_RESET:earliest}
spring.kafka.consumer.key-deserializer=${KAFKA_KEY_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
spring.kafka.consumer.value-deserializer=${KAFKA_VALUE_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}

#spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=${KAFKA_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
spring.kafka.producer.value-serializer=${KAFKA_VALUE_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/servicedb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=5m